import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/providers/store-provider";
import UserBar from "@/components/layout/user-bar";
import Footer from "@/components/layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background overflow-x-hidden antialiased`}
      >
        <StoreProvider>
          <>
            <UserBar />
            <div className="pt-[72px] md:pt-28">{children}</div>
            <Footer />
          </>
        </StoreProvider>
      </body>
    </html>
  );
}
